# Generated by Django 5.2.7 on 2025-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carregistrationpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimg', models.ImageField(upload_to='images/')),
                ('carname', models.CharField(max_length=15)),
                ('cardesc', models.CharField(max_length=500)),
                ('carprice', models.IntegerField()),
                ('carcate', models.CharField(max_length=200)),
                ('carmonth', models.CharField(default='none', max_length=10)),
                ('carmodel', models.CharField(default='none', max_length=15)),
                ('carcolor', models.CharField(default='none', max_length=15)),
                ('carfuel', models.CharField(default='none', max_length=20)),
                ('carversion', models.CharField(default='none', max_length=20)),
                ('caralter', models.CharField(default='none', max_length=10)),
                ('carowner', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userregisterpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=30)),
                ('userphone', models.IntegerField()),
                ('userimg', models.ImageField(upload_to='images/')),
                ('userpass', models.CharField(max_length=15)),
            ],
        ),
    ]
