# Generated by Django 5.2.7 on 2025-10-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregistrationpage',
            name='carkilo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carregistrationpage',
            name='caryear',
            field=models.IntegerField(default=0),
        ),
    ]
