# Generated by Django 5.2.7 on 2025-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcar', '0002_carregistrationpage_carkilo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregistrationpage',
            name='carname',
            field=models.CharField(max_length=35),
        ),
    ]
