# Generated by Django 5.2.7 on 2025-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcar', '0003_alter_carregistrationpage_carname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregistrationpage',
            name='cardesc',
            field=models.CharField(max_length=800),
        ),
    ]
