# Generated by Django 5.2.7 on 2025-12-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcar', '0004_alter_carregistrationpage_cardesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishitemcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcar.carregistrationpage')),
            ],
        ),
    ]
