# Generated by Django 5.2.7 on 2026-03-04 08:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcar', '0005_wishitemcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregistrationpage',
            name='carimg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userregisterpage',
            name='userimg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
